package com.altaira.backend.service;

import com.altaira.backend.entity.ClientEntity;
import com.altaira.backend.entity.OnboardingTaskEntity;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.util.List;

@Service
public class SignedContractPdfService {

    private final String contractPdfPath;

    public SignedContractPdfService(@Value("${altaira.onboarding.contract-pdf-path:}") String contractPdfPath) {
        this.contractPdfPath = contractPdfPath == null ? "" : contractPdfPath.trim();
    }

    public byte[] buildSignedContractEvidence(ClientEntity client, OnboardingTaskEntity task) {
        try {
            if (!contractPdfPath.isBlank()) {
                File contractFile = new File(contractPdfPath);
                if (contractFile.exists() && contractFile.isFile()) {
                    return stampExistingContract(contractFile, client, task);
                }
            }

            return createSignatureReceipt(client, task);
        } catch (IOException ex) {
            throw new IllegalStateException("Could not create signed contract PDF evidence", ex);
        }
    }

    private byte[] stampExistingContract(File contractFile, ClientEntity client, OnboardingTaskEntity task) throws IOException {
        try (PDDocument document = Loader.loadPDF(contractFile)) {
            PDPage page = document.getPage(document.getNumberOfPages() - 1);
            PDFontSet fonts = fonts();

            try (PDPageContentStream contentStream = new PDPageContentStream(
                    document,
                    page,
                    PDPageContentStream.AppendMode.APPEND,
                    true,
                    true
            )) {
                contentStream.setFont(fonts.regular(), 8);
                contentStream.beginText();
                contentStream.newLineAtOffset(40, 40);
                contentStream.showText("Altaira Labs written signature audit: " + auditLine(client, task));
                contentStream.endText();
            }

            ByteArrayOutputStream output = new ByteArrayOutputStream();
            document.save(output);
            return output.toByteArray();
        }
    }

    private byte[] createSignatureReceipt(ClientEntity client, OnboardingTaskEntity task) throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            document.addPage(page);
            PDFontSet fonts = fonts();

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.setFont(fonts.bold(), 18);
                contentStream.beginText();
                contentStream.newLineAtOffset(56, 760);
                contentStream.showText("Altaira Labs - Signed Service Agreement Evidence");
                contentStream.endText();

                contentStream.setFont(fonts.regular(), 10);
                float y = 715;
                for (String line : receiptLines(client, task)) {
                    contentStream.beginText();
                    contentStream.newLineAtOffset(56, y);
                    contentStream.showText(cleanPdfText(line));
                    contentStream.endText();
                    y -= 22;
                }
            }

            ByteArrayOutputStream output = new ByteArrayOutputStream();
            document.save(output);
            return output.toByteArray();
        }
    }

    private List<String> receiptLines(ClientEntity client, OnboardingTaskEntity task) {
        return List.of(
                "Client: " + nullSafe(client.getCompany()),
                "Contact: " + nullSafe(client.getName()) + " <" + nullSafe(client.getEmail()) + ">",
                "Task: " + nullSafe(task.getTitle()),
                "Signer full name: " + nullSafe(task.getSignatureFullName()),
                "Document ID: " + nullSafe(task.getSignatureDocumentId()),
                "Consent accepted: " + task.isSignatureConsent(),
                "Signed at: " + nullSafe(task.getSignedAt()),
                "IP address: " + nullSafe(task.getSignedIp()),
                "User-Agent: " + nullSafe(task.getSignedUserAgent()),
                "Server timestamp: " + Instant.now(),
                "",
                "This PDF is an onboarding audit artifact generated by Altaira Labs.",
                "If a formal contract PDF template is configured, this audit line is stamped onto that file."
        );
    }

    private String auditLine(ClientEntity client, OnboardingTaskEntity task) {
        return "client=" + nullSafe(client.getId()) +
                "; signer=" + nullSafe(task.getSignatureFullName()) +
                "; documentId=" + nullSafe(task.getSignatureDocumentId()) +
                "; signedAt=" + nullSafe(task.getSignedAt()) +
                "; ip=" + nullSafe(task.getSignedIp());
    }

    private String cleanPdfText(String value) {
        return nullSafe(value).replaceAll("[\\r\\n\\t]+", " ");
    }

    private String nullSafe(Object value) {
        return value == null ? "" : String.valueOf(value);
    }

    private PDFontSet fonts() {
        return new PDFontSet(
                new PDType1Font(Standard14Fonts.FontName.HELVETICA),
                new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)
        );
    }

    private record PDFontSet(PDType1Font regular, PDType1Font bold) {}
}
