package com.altaira.backend.provisioning;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

final class ProvisioningScenarioAuditReport {

    private ProvisioningScenarioAuditReport() {}

    static void write(Path reportPath, List<ProvisioningScenarioAuditResult> unsortedResults) throws IOException {
        List<ProvisioningScenarioAuditResult> results = unsortedResults.stream()
                .sorted(Comparator.comparing(result -> result.scenario().id()))
                .toList();
        long passCount = results.stream().filter(ProvisioningScenarioAuditResult::passes).count();
        long mismatchCount = results.size() - passCount;

        StringBuilder report = new StringBuilder();
        report.append("# Provisioning Engine Scenario Audit\n\n")
                .append("> Generated by `ProvisioningDecisionEngineScenarioAuditTests`. ")
                .append("The suite evaluates Engine v2 and calls no external API.\n\n")
                .append("## 1. Executive result\n\n")
                .append("- Total scenarios evaluated: **").append(results.size()).append("**\n")
                .append("- PASS: **").append(passCount).append("**\n")
                .append("- MISMATCH: **").append(mismatchCount).append("**\n")
                .append("- Engine v1 baseline: **5 PASS / 45 MISMATCH**\n")
                .append("- Decision providers: metadata-only dry-run providers\n")
                .append("- External calls executed: **0**\n")
                .append("- Real customer data used: **0**\n\n")
                .append("A `MISMATCH` is an audit finding, not a Maven failure. It means the current ")
                .append("engine differs from the approved expected outcome in at least one dimension.\n\n");

        appendServiceSummary(report, results);
        appendDemoSummary(report, results);
        appendRouteFailures(report, results);
        appendToolDeltas(report, results);
        appendMissingFields(report, results);
        appendEngineV2Conclusions(report, results);
        appendDetails(report, results);

        Files.createDirectories(reportPath.getParent());
        Files.writeString(reportPath, report.toString(), StandardCharsets.UTF_8);
    }

    private static void appendServiceSummary(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        report.append("## 2. Summary by service\n\n")
                .append("| Service | Total | PASS | MISMATCH |\n")
                .append("|---|---:|---:|---:|\n");
        for (String service : List.of("Web", "Booking", "CRM", "Automation", "Dashboard")) {
            List<ProvisioningScenarioAuditResult> serviceResults = results.stream()
                    .filter(result -> !result.scenario().demo())
                    .filter(result -> service.equals(result.scenario().service()))
                    .toList();
            long passes = serviceResults.stream().filter(ProvisioningScenarioAuditResult::passes).count();
            report.append("| ").append(service).append(" | ")
                    .append(serviceResults.size()).append(" | ")
                    .append(passes).append(" | ")
                    .append(serviceResults.size() - passes).append(" |\n");
        }
        report.append("\n");
    }

    private static void appendDemoSummary(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        report.append("## 3. Four priority demos\n\n")
                .append("All names are fictional and no real business is represented as a client.\n\n")
                .append("| Demo | Result | Expected route | Actual route | Main delta |\n")
                .append("|---|---|---|---|---|\n");
        results.stream()
                .filter(result -> result.scenario().demo())
                .forEach(result -> report.append("| ")
                        .append(escape(result.scenario().name())).append(" | ")
                        .append(result.passes() ? "PASS" : "MISMATCH").append(" | `")
                        .append(result.scenario().expected().route()).append("` | `")
                        .append(result.actualRoute()).append("` | ")
                        .append(escape(firstMismatch(result))).append(" |\n"));
        report.append("\n");
    }

    private static void appendRouteFailures(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        Map<String, Long> failures = results.stream()
                .filter(result -> !result.scenario().expected().route().equals(result.actualRoute()))
                .collect(Collectors.groupingBy(
                        result -> result.scenario().expected().route(),
                        LinkedHashMap::new,
                        Collectors.counting()
                ));
        report.append("## 4. Routes with most mismatches\n\n")
                .append("| Expected route | Route mismatches |\n")
                .append("|---|---:|\n");
        failures.entrySet().stream()
                .sorted(Map.Entry.<String, Long>comparingByValue().reversed()
                        .thenComparing(Map.Entry.comparingByKey()))
                .forEach(entry -> report.append("| `").append(entry.getKey()).append("` | ")
                        .append(entry.getValue()).append(" |\n"));
        if (failures.isEmpty()) {
            report.append("| None | 0 |\n");
        }
        report.append("\n");
    }

    private static void appendToolDeltas(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        Map<String, Long> overIncluded = countToolDeltas(results, result -> difference(
                result.actualIncludedTools(), result.scenario().expected().includedTools()));
        Map<String, Long> missing = countToolDeltas(results, result -> difference(
                result.scenario().expected().includedTools(), result.actualIncludedTools()));

        report.append("## 5. Tool selection deltas\n\n")
                .append("### Most over-included\n\n");
        appendCountTable(report, "Tool", overIncluded);
        report.append("### Most frequently missing\n\n");
        appendCountTable(report, "Tool", missing);
    }

    private static Map<String, Long> countToolDeltas(
            List<ProvisioningScenarioAuditResult> results,
            Function<ProvisioningScenarioAuditResult, List<String>> extractor
    ) {
        return results.stream()
                .flatMap(result -> extractor.apply(result).stream())
                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
    }

    private static void appendMissingFields(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        Map<String, Long> missingFields = results.stream()
                .flatMap(result -> result.scenario().missingFormFields().stream())
                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));
        report.append("## 6. Missing form fields\n\n")
                .append("These are inputs required to explain the approved expectation but not available ")
                .append("as structured questions in the current qualification forms.\n\n");
        appendCountTable(report, "Field", missingFields);
    }

    private static void appendEngineV2Conclusions(
            StringBuilder report,
            List<ProvisioningScenarioAuditResult> results
    ) {
        long passingDemos = results.stream()
                .filter(result -> result.scenario().demo())
                .filter(ProvisioningScenarioAuditResult::passes)
                .count();
        report.append("## 7. Engine v2 conclusions\n\n")
                .append("1. The engine now returns `TrackDecision[]` and a composed route key; priority demos passing: **")
                .append(passingDemos).append("/4**.\n")
                .append("2. Route families now distinguish managed CMS, ecommerce, booking SaaS, external CRM, ")
                .append("managed automation and BI from custom development.\n")
                .append("3. Infrastructure is selected per track, then shared GitHub, Jira, Drive, Auth, Neon, ")
                .append("Resend and Calendar decisions are deduplicated.\n")
                .append("4. Automation level, rule ID, matched signals, confidence, manual-decision flag, tools, ")
                .append("manual steps and risks are available on every track.\n")
                .append("5. Remaining mismatches identify discovery or policy refinements; they do not execute providers.\n\n");
    }

    private static void appendDetails(StringBuilder report, List<ProvisioningScenarioAuditResult> results) {
        report.append("## 8. Scenario details\n\n");
        for (ProvisioningScenarioAuditResult result : results) {
            ProvisioningAuditScenario scenario = result.scenario();
            report.append("### ").append(scenario.id()).append(" - ")
                    .append(scenario.name()).append("\n\n")
                    .append("- Service: ").append(scenario.service())
                    .append(scenario.demo() ? " (priority demo)" : "").append("\n")
                    .append("- Result: **").append(result.passes() ? "PASS" : "MISMATCH").append("**\n")
                    .append("- Simulated responses: `").append(escapeCode(scenario.responses().toString())).append("`\n")
                    .append("- Recommended services: `").append(scenario.recommendedServices()).append("`\n")
                    .append("- Expected requirements: `").append(scenario.expected().requirements()).append("`\n")
                    .append("- Actual requirements: `").append(result.actualRequirements()).append("`\n")
                    .append("- Expected route: `").append(scenario.expected().route()).append("`\n")
                    .append("- Actual route: `").append(result.actualRoute()).append("`\n")
                    .append("- Actual tracks: `").append(result.actualTracks()).append("`\n")
                    .append("- Matched rules: `").append(result.actualRuleIds()).append("`\n")
                    .append("- Shared resources: `").append(result.actualSharedResources()).append("`\n")
                    .append("- Expected included tools: `").append(scenario.expected().includedTools()).append("`\n")
                    .append("- Actual included tools: `").append(result.actualIncludedTools()).append("`\n")
                    .append("- Expected excluded tools: `").append(scenario.expected().excludedTools()).append("`\n")
                    .append("- Actual explicit exclusions: `").append(result.actualExcludedTools()).append("`\n")
                    .append("- Expected / actual level: `").append(scenario.expected().automationLevel())
                    .append("` / `").append(result.actualAutomationLevel()).append("`\n")
                    .append("- Expected manual steps: `").append(scenario.expected().manualSteps()).append("`\n")
                    .append("- Actual manual steps: `").append(result.actualManualSteps()).append("`\n")
                    .append("- Expected risk keywords: `").append(scenario.expected().riskKeywords()).append("`\n")
                    .append("- Actual risks: ").append(result.actualRisks()).append("\n")
                    .append("- Missing structured form fields: `").append(scenario.missingFormFields()).append("`\n")
                    .append("- Deltas: ").append(result.passes() ? "none" : result.mismatches()).append("\n\n");
        }
    }

    private static void appendCountTable(StringBuilder report, String heading, Map<String, Long> counts) {
        report.append("| ").append(heading).append(" | Scenarios |\n")
                .append("|---|---:|\n");
        counts.entrySet().stream()
                .sorted(Map.Entry.<String, Long>comparingByValue().reversed()
                        .thenComparing(Map.Entry.comparingByKey()))
                .forEach(entry -> report.append("| `").append(entry.getKey()).append("` | ")
                        .append(entry.getValue()).append(" |\n"));
        if (counts.isEmpty()) {
            report.append("| None | 0 |\n");
        }
        report.append("\n");
    }

    private static List<String> difference(List<String> left, List<String> right) {
        List<String> difference = new ArrayList<>(left);
        difference.removeAll(right);
        return difference;
    }

    private static String firstMismatch(ProvisioningScenarioAuditResult result) {
        return result.mismatches().isEmpty() ? "No delta" : result.mismatches().getFirst();
    }

    private static String escape(String value) {
        return value.replace("|", "\\|").replace("\n", " ");
    }

    private static String escapeCode(String value) {
        return value.replace("`", "'").replace("\n", " ");
    }
}
