package com.altaira.backend.model;

public enum ProvisioningRoute {
    COMPOSITE,
    PROVISION_WEB_STATIC,
    PROVISION_WEB_CMS,
    PROVISION_WEB_CUSTOM,
    PROVISION_ECOMMERCE_PLATFORM,
    PROVISION_ECOMMERCE_CUSTOM,
    PROVISION_BOOKING_SAAS,
    PROVISION_BOOKING_CUSTOM,
    PROVISION_CRM_ALTAIRA,
    PROVISION_CRM_EXTERNAL,
    PROVISION_AUTOMATION_MANAGED,
    PROVISION_AUTOMATION_CUSTOM,
    PROVISION_DASHBOARD_BI,
    PROVISION_DASHBOARD_CUSTOM
}
